
name: Go

on:
  push:
    branches: [ master ]
     
# https://github.com/aws-actions/configure-aws-credentials

jobs:
  build-debian:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::188154480716:role/github-actions-credentials
        role-session-name: gh-action-define
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Test install
      run: |
        make clean
        make VERSION=1.0-dev package-deb 
        sudo apt install ./build/*.deb
        define -version
    - name: Upload .deb binary to S3
      run: |
        aws s3 cp ./build/define*.deb s3://github-artifacts-zeebrow/define/latest-dev/linux/amd64/
        aws s3 cp ./build/linux/amd64/define* s3://github-artifacts-zeebrow/define/binaries/linux/

  build-windows-amd64:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::188154480716:role/github-actions-credentials
        role-session-name: gh-action-define
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build and test
      run: |
        go install .
        go build .
        define.exe -version
    - name: Upload .exe to S3
      run: |
        aws s3 cp ./define*.exe s3://github-artifacts-zeebrow/define/binaries/windows/
