
name: Go

on:
  push:
    branches: [ master ]

jobs:
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test install
      run: make package-deb && sudo apt install ./build/define.deb

    - name: Test .deb installed properly
      run: define -version

  build-windows-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build and test
      run: |
        go install .
        go build .
        define.exe -version
